---
- name: Check for Docker
  stat: path=/etc/init.d/docker
  register: docker_status

- name: Get script
  shell:
    cmd: curl -fsSL "{{ docker_install }}" -o get-docker.sh
  when: not docker_status.stat.exists

- name: Run script
  shell:
    cmd: sh get-docker.sh
  when: not docker_status.stat.exists

- name: Install docker packages
  package: 
    name:
      - pip
      - python3-docker
    state: latest

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user "{{ username }}" to group docker
  user: 
    name: "{{ username }}"
    groups:
      - docker
    append: yes

- name: Chmod the data folder
  file:
    dest: "{{ docker_directory }}"
    owner: "{{ username }}"
    group: docker
    state: directory
    recurse: yes