install_traefik: true
install_homer: true
install_jellyfin: true
install_pihole: true
install_qbittorrent: true
install_sonarr: true
install_jackett: true
install_radarr: true
install_bazarr: true
install_uptime_kuma: true
install_prometheus: true
install_grafana: true
install_x735: true

# Shared

traefik_name: Traefik
homer_name: Homer
jellyfin_name: Jellyfin
pihole_name: Pi-hole
qbittorrent_name: qBittorrent
sonarr_name: Sonarr
jackett_name: Jackett
radarr_name: Radarr
bazarr_name: Bazarr
uptime_kuma_name: Uptime Kuma
prometheus_name: Prometheus
grafana_name: Grafana

services:
  - "{{ traefik_name }}"
  - "{{ homer_name }}"
  - "{{ jellyfin_name }}"
  - "{{ pihole_name }}"
  - "{{ qbittorrent_name }}"
  - "{{ sonarr_name }}"
  - "{{ jackett_name }}"
  - "{{ radarr_name }}"
  - "{{ bazarr_name }}"
  - "{{ uptime_kuma_name }}"
  - "{{ prometheus_name }}"
  - "{{ grafana_name }}"

docker_network_name: "{{ domain }}"

# Traefik 

traefik_port: "81"
certs_dir: /opt/certs

# Homer

homer_port: "8080"

# Jellyfin

jellyfin_port: "8096"

# Pi-hole

pihole_port: "80"

# qBittorent

qbittorrent_port: "8000"

# Sonarr

sonarr_port: "8989"

# Jackett

jackett_port: "9117"

# Radarr

radarr_port: "7878"

# Bazarr

bazarr_port: "6767"

# Uptime Kuma

uptime_kuma_port: "3001"

# Prometheus

node_exporter_name: node_exporter

prometheus_port: "9090"
node_exporter_port: "9100"

# Grafana

grafana_port: "3000"

# x735

x735_repo: https://github.com/geekworm-com/x735-v2.5.git