install_traefik: true
install_homer: true
install_jellyfin: true
install_pihole: true
install_qbittorrent: true
install_sonarr: true
install_jackett: true
install_radarr: true
install_bazarr: true
install_uptime_kuma: true
install_x735: true

# Shared

traefik_name: Traefik
homer_name: Homer
jellyfin_name: Jellyfin
pihole_name: Pi-hole
qbittorrent_name: qBittorrent
sonarr_name: Sonarr
jackett_name: Jackett
radarr_name: Radarr
bazarr_name: Bazarr
uptime_kuma_name: Uptime Kuma

services:
  - "{{ traefik_name }}"
  - "{{ homer_name }}"
  - "{{ jellyfin_name }}"
  - "{{ pihole_name }}"
  - "{{ qbittorrent_name }}"
  - "{{ sonarr_name }}"
  - "{{ jackett_name }}"
  - "{{ radarr_name }}"
  - "{{ bazarr_name }}"
  - "{{ uptime_kuma_name }}"

docker_network_name: "{{ domain }}"

# Traefik 

traefik_port: "81"

certs_dir: /opt/certs

# Homer

homer_port: "8080"

# Jellyfin

jellyfin_port: "8096"

# Pi-hole

pihole_port: "80"

# qBittorent

qbittorrent_port: "8000"

# sonarr

sonarr_port: "8989"

# jackett

jackett_port: "9117"

# radarr

radarr_port: "7878"

# bazarr

bazarr_port: "6767"

# uptime kuma

uptime_kuma_port: "3001"

# x735

x735_repo: https://github.com/geekworm-com/x735-v2.5.git