install_traefik: true
install_homer: true
install_jellyfin: true
install_pihole: true
install_qbittorent: true
install_sonarr: true
install_jackett: true
install_radarr: true
install_bazarr: true
install_x735: true

# Shared

traefik_name: Traefik
homer_name: Homer
jellyfin_name: Jellyfin
pihole_name: Pi-hole
qbittorent_name: qBittorent
sonarr_name: Sonarr
jackett_name: Jackett
radarr_name: Radarr
bazarr_name: Bazarr

# Traefik 

traefik_port: "81"

certs_dir: /opt/certs

# Homer

homer_port: "8080"

services:
  - "{{ traefik_name }}"
  - "{{ homer_name }}"
  - "{{ jellyfin_name }}"
  - "{{ pihole_name }}"
  - "{{ qbittorent_name }}"
  - "{{ sonarr_name }}"
  - "{{ jackett_name }}"
  - "{{ radarr_name }}"
  - "{{ bazarr_name }}"

# Jellyfin

jellyfin_port: "8096"

# Pi-hole

pihole_port: "80"

# qBittorent

qbittorent_port: "8000"

# sonarr

sonarr_port: "8989"

# jackett

jackett_port: "9117"

# radarr

radarr_port: "7878"

# bazarr

bazarr_port: "6767"

# x735

x735_repo: https://github.com/geekworm-com/x735-v2.5.git