install_traefik: true

install_homer: true

install_jellyfin: true

install_pihole: true

install_x735: true

# Shared

traefik_name: Traefik
homer_name: Homer
jellyfin_name: Jellyfin
pihole_name: Pi-hole

# Traefik 

traefik_port: "81"

certs_dir: /opt/certs

# Homer

homer_port: "8080"

services:
  - "{{ traefik_name }}"
  - "{{ homer_name }}"
  - "{{ jellyfin_name }}"
  - "{{ pihole_name }}"

# Jellyfin

jellyfin_port: "8096"

# Pi-hole

pihole_port: "80"

# x735

x735_repo: https://github.com/geekworm-com/x735-v2.5.git