---
- name: Make Bazarr directory
  file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    recurse: yes
  loop:
    - "{{ docker_directory }}/{{ bazarr_name | lower }}"
    - "{{ docker_directory }}/{{ bazarr_name | lower }}/config"

- name: Check the Bazarr container is created and running
  docker_container:
    name: "{{ bazarr_name }}"
    hostname: "{{ bazarr_name | lower }}"
    image: "lscr.io/linuxserver/bazarr"
    pull: true
    state: "started"
    restart_policy: "unless-stopped"
    env:
      "TZ": "Europe/London"
      "PUID": "1000"
      "PGID": "1000"
    volumes: 
      - "{{ disk_path }}:/media"
      - "{{ docker_directory }}/{{ bazarr_name | lower }}/config:/config"
      - "{{ docker_directory }}/{{ qbittorent_name | lower }}/downloads:/downloads"
    labels:
      "traefik.enable": "true"
      "traefik.http.routers.bazarr_route.entrypoints": "websecure"
      "traefik.http.routers.bazarr_route.rule": "Host(`{{ bazarr_name | lower }}.{{ domain }}`)"
      "traefik.http.routers.bazarr_route.service": "bazarr_service"
      "traefik.http.routers.bazarr_route.tls": "true"
      "traefik.http.routers.bazarr_route.tls.certResolver": "letsencrypt"
      "traefik.http.services.bazarr_service.loadbalancer.server.port": "{{ bazarr_port }}"
    networks:
      - name: traefik_public