---
- name: Make Homer directory
  file:
    path: "{{ docker_directory}}/homer/"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    recurse: yes

- name: Copy config template to Homer directory
  template:
    src: ../files/homer/homer-config.yml.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    dest: "{{ docker_directory }}/homer/config.yml"
    recurse: yes

- name: Copy image assets to Homer directory
  copy: 
    src: "../files/homer/assets/"
    owner: "{{ username }}"
    group: "{{ username }}"
    dest: "{{ docker_directory }}/homer/"
    recurse: yes

- name: Check the Homer container is created and running
  docker_container:
    name: "homer"
    image: "b4bz/homer"
    pull: true
    state: "started"
    restart_policy: "unless-stopped"
    volumes: 
      - "{{ docker_directory }}/homer/:/www/assets/"
    labels:
      "traefik.enable": "true"
      "traefik.http.routers.homer_route.entrypoints": "websecure"
      "traefik.http.routers.homer_route.rule": "Host(`homer.local`)"
      "traefik.http.routers.homer_route.service": "homer_service"
      "traefik.http.routers.homer_route.tls": "true"
      "traefik.http.services.homer_service.loadbalancer.server.port": "8080"
    networks:
      - name: traefik_public