---
- name: Make Jellyfin directories
  file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    recurse: yes
  loop:
  - "{{ docker_directory }}/jellyfin"
  - "{{ docker_directory }}/jellyfin/config"
  - "{{ docker_directory }}/jellyfin/cache"


- name: Check the Jellyfin container is created and running
  docker_container:
    name: "jellyfin"
    image: "jellyfin/jellyfin"
    pull: true
    state: "started"
    restart_policy: "unless-stopped"
    ports: "{{ jellyfin_port }}:{{ jellyfin_port }}"
    volumes: 
      - "{{ docker_directory }}/jellyfin/config:/config"
      - "{{ docker_directory }}/jellyfin/cache:/cache"
      - "{{ disk_path }}:/media"