---
- include_tasks: traefik.yml
  when: install_traefik | bool

- include_tasks: homer.yml
  when: install_homer | bool

- include_tasks: jellyfin.yml
  when: install_jellyfin | bool

- include_tasks: pi-hole.yml
  when: install_pihole | bool

- include_tasks: qbittorrent.yml
  when: install_qbittorrent | bool

- include_tasks: sonarr.yml
  when: install_sonarr | bool

- include_tasks: jackett.yml
  when: install_jackett | bool

- include_tasks: radarr.yml
  when: install_radarr | bool

- include_tasks: bazarr.yml
  when: install_bazarr | bool
  
- include_tasks: x735.yml 
  when: install_x735 | bool