---
- name: Make qBittorent directory
  file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    recurse: yes
  loop:
    - "{{ docker_directory }}/{{ qbittorent_name | lower }}"
    - "{{ docker_directory }}/{{ qbittorent_name | lower }}/config"
    - "{{ docker_directory }}/{{ qbittorent_name | lower }}/downloads"

- name: Check the qBittorent container is created and running
  docker_container:
    name: "{{ qbittorent_name }}"
    hostname: "{{ qbittorent_name | lower }}"
    image: "lscr.io/linuxserver/qbittorrent"
    pull: true
    state: "started"
    restart_policy: "unless-stopped"
    env:
      "TZ": "Europe/London"
      "WEBUI_PORT": "{{ qbittorent_port }}"
      "PASSWORD": "{{ qbittorent_password }}"
      "PUID": "1000"
      "PGID": "1000"
    ports:
      - 6881:6881
    volumes: 
      - "{{ docker_directory }}/{{ qbittorent_name | lower }}/config:/config"
      - "{{ docker_directory }}/{{ qbittorent_name | lower }}/downloads:/downloads"
    labels:
      "traefik.enable": "true"
      "traefik.http.routers.qbittorent_route.entrypoints": "websecure"
      "traefik.http.routers.qbittorent_route.rule": "Host(`{{ qbittorent_name | lower }}.{{ domain }}`)"
      "traefik.http.routers.qbittorent_route.service": "qbittorent_service"
      "traefik.http.routers.qbittorent_route.tls": "true"
      "traefik.http.routers.qbittorent_route.tls.certResolver": "letsencrypt"
      "traefik.http.services.qbittorent_service.loadbalancer.server.port": "{{ qbittorent_port }}"
    networks:
      - name: traefik_public